if(NOT DEFINED MSI_KEYBOARD_DEVICE_CONFIG
   OR NOT DEFINED MSI_KEYBOARD_GENERATED_HEADER
   OR NOT DEFINED MSI_KEYBOARD_UDEV_OUTPUT)
    message(FATAL_ERROR
        "MSI_KEYBOARD_DEVICE_CONFIG, MSI_KEYBOARD_GENERATED_HEADER, and MSI_KEYBOARD_UDEV_OUTPUT are required")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/DeviceDefinitions.cmake")
msi_keyboard_generate_device_files(
    "${MSI_KEYBOARD_DEVICE_CONFIG}"
    "${MSI_KEYBOARD_GENERATED_HEADER}"
    "${MSI_KEYBOARD_UDEV_OUTPUT}"
)
